### ISSUE TITLE
Multiple issues to review

### ISSUE THREAD

**Issue by topr** [CodeNarc/CodeNarc#105]
Quite a long time ago when I was adapting CodeNarc in the company I work for and I gathered some issues in a text file with the intention to organize them well and post here, each as separate 'submit new issue'.

I've never done that though and it has got covered with dust till now... I thought it may still be better to show what I had come across and review together which ones are still relevant so we could address and fix such. Here we go:
## 
1. maven plugin, violations summary incorrect message.
   (https://github.com/gleclaire/codenarc-maven-plugin/blob/master/src/main/groovy/org/codehaus/mojo/codenarc/CodeNarcMojo.groovy#L447)
   Probably a copy-paste mistake.
   For maxPriority2Violations exceeded 'totalPriority1Violations exceeded threshold...' message is printed.
2. maven plugin, classpath is not propagated.
   Project POM's dependencies are not passed as classpath for CodeNarc sources compilation.
   Specifying libs as plugin dependencies doesn't work either (it would be redundant and ugly anyway).
   The same applies to gradle plugin and is related to 'enchanced' ruleset.
3. `SpaceAroundMapEntryColon` incorrect `characterAfterColonRegex` default value
   Probably copy-paste mistake.
   Default regexp for `characterAfterColonRegex` is the same as for `characterBeforeColonRegex` property - capital `\S` (non white space) instead of `\s` (whitespace).
4. `LineLength` lacks of skip policy configuration.
   It's not possible to specify prefix or regexp for skipping particular lines by this rule.
   For example it's pretty pointless to break line in the middle of long import statements (long package + class name).
   Such statements can't be suppressed any other way either.
5. `SpaceAfterClosingBrace` is violated by anonymous implementation.
   When anonymous implementation instance is passed as last method argument the rule going to be violated unnecessarily.
   Example:
   
   ``` groovy
   foo.bar(new Whatever() {
       void doSomething() {/*...*/}
   })
   ```
   
   The last line will violate the rule, which is consistent behaviour but annoying.
6. `SpaceBeforeOpeningBrace` is violated by Closure passed as method argument.
   The rule is violated unnecessarily when inline Closure is passed as method argument and surrounded by round brackets.
   Example: `foo.bar({ println 'rule is violated' })`
   This example isn't the best one, as round brackets can be omitted.
   But there are specific situations when it might be necessary like:
   - Closure is not passed as the last/only argument
   - more than one Closure are passed
   - left or right shift operator is used to 'concatenate' closures
   
   The above specific example may violate some other `UnnecessaryBracket` rule,
   but shouldn't violate `SpaceBeforeOpeningBrace`.
7. `AssignCollectionSort` violates map sorting.
   Method sort() called on map instance doesn't mutate the map itself, only returns another sorted instance.
   Quote from api docs: (...) The original map is unchanged.
   http://groovy.codehaus.org/groovy-jdk/java/util/Map.html#sort()
   Despite the above violation of the rule occurs in such case:
   
   ``` groovy
   Map someMap = [:]
   Map sortedMap = someMap.sort()
   ```
   
   It should complain only about 'sortable' collections (f.e. Set is not the case as well)
8. `ExplicitLinkedList` and static compilation issue.
   `ExplicitLinkedList` suggest instantation with `[] as Queue` even when it's not possible.
   This involves `@CompileStatic` or `@TypeChecked` usage.
   In such cases rule shouldn't be violated.
9. XSD schema expects having XML configuration tags in specific order.
   Despite the fact that configuration is processed correctly no matter what is the tags order,
   configuration tags has to be ordered in specific way to remain valid against ruleset-schema.xsd.
   Example valid against schema:
   
   ``` xml
   <ruleset>
       <ruleset-ref path='somerules.xml'/>
       <ruleset-ref path='otherrules.xml'/>
       <rule class='some.package.SomeRule'/>
   </ruleset>
   ```
   
   Example the exact same configuration but invalid against schema:
   
   ``` xml
   <ruleset>
       <ruleset-ref path='somerules.xml'/>
       <rule class='some.package.SomeRule'/>
       <ruleset-ref path='otherrules.xml'/>
   </ruleset>
   ```
   
   There is more similar cases like the above. For example <ruleset-ref/>'s nested
   <include/> tag has to be after <rule-config/> but before <exclude/>
10. `SerializableClassMustDefineSerialVersionUID` is violated for enum types.
    `SerializableClassMustDefineSerialVersionUID` complains about enum type not having serialVersionUID.
    In the same time there is a rule `EnumCustomSerializationIgnored` which complains about the exact opposite.
11. `@SuppressWarnings('MethodSize')` doesn't work on constructor.
12. How about `UnnecessarySetter` rule?
13. `UnnecessaryGetter` rule is not violated by boolean getters like `isSomething()`.
14. `UnnecessaryPackageReference` rule is violated on groovy scripts without any reason.
    Consider Groovy script file:
    
    ``` groovy
    package com.something.scripts
    
    someString = 'Y U VIOLATE?'
    println someString
    ```
    
    When compiled it's violated as follows:
    
    > [SRC]someString = 'Y U VIOLATE?'
    > [MSG]Specifying the package name is not necessary for groovy.lang.Script
    
    Groovy ver 2.1.7
15. `UnusuedPrivateMethod` rule is violated despite existing usage.
    It happens when private method is called on an instance created within static method of the same class.
    Example:
    
    ``` groovy
    class Something {
    
        static void whatever() {
                new Something().whasup()
        }
    
        private void whasup() {
                println 'whasup!'
        }
    }
    ```

**Comment by topr** [comment]
I see that the number one has been addressed already.

**Comment by chrismair** [comment]
Number 4 has been partially addressed ignoring import and package statements by default.
Number 5 does not appear to be a problem anymore.

**Comment by chrismair** [comment]
Number 6 is at least partially resolved (there are tests for passing closures as arguments)
Number 10 appears to be resolved (there are tests for enums).

**Comment by chrismair** [comment]
Number 11 was fixed by #109: Enable @SuppressWarnings to work on constructors

**Comment by chrismair** [comment]
Number 14 appears to be fixed as well (there are tests for package declarations on groovy scripts)

**Comment by topr** [comment]
Thanks for update on that.
I'll have a look on remaining ones in a spare moment.

**Comment by chrismair** [comment]
Number 4 has been addressed by #144: LineLength rule: Add ignoreLineRegex.

**Comment by jlstrater** [comment]
@topr Have you had time to look at which of these are still relevant? If so, can I propose that we close this issue and open new issues for the last items? It's difficult to figure out what to work on next in this thread.

**Comment by chrismair** [comment]
Closing. Open new, separate issues if any of the above are still relevant.
