### ISSUE TITLE
http://codenarc.org/ available via HTTPS

### ISSUE THREAD

**Issue by szpak** [CodeNarc/CodeNarc#461]
As you use GitHub pages for the project page (https://codenarc.github.io/CodeNarc/), maybe it would be possible to use HTTPS for `codenarc.org`?

GitHub [supports](https://github.blog/2018-05-01-github-pages-custom-domains-https/) is (unless you have some problems with domain delegation).

**Comment by tlefevre** [comment]
HTTPS is already used, but not enforced - is that what you mean?

**Comment by szpak** [comment]
It is for `https://codenarc.github.io/`, but not for `https://codenarc.org/`.

![image](https://user-images.githubusercontent.com/148013/75960037-a51b0f80-5ebf-11ea-8c49-aff9641d6707.png)

![image](https://user-images.githubusercontent.com/148013/75960064-b106d180-5ebf-11ea-9897-3a4f1993ea5e.png)

 If you control the domain (i.e. can change the DNS entries) it should be possible to [configure it](https://github.blog/2018-05-01-github-pages-custom-domains-https/) to support HTTPS via GitHub.

Regarding enforcement for `https://codenarc.github.io/`, IMHO it would be good to redirect people to HTTPS version (while enter `http://codenarc.github.io/`). Number of incompatible devices should be minimal (old Android? Brackberry? IE6?) and usually people should still be able to click "proceed anyway". However, as you mention `codenarc.org` in your README, it would be good to sort it out first.

**Comment by chrismair** [comment]
I have enabled HTTPS on the *codenarc.org* domain and enforced HTTPS on the GitHub side. I also committed changes to switch CodeNarc URLs to HTTPS, on the web pages and also in the report writer classes. Feel free to reopen this issue if I missed anything.

**Comment by szpak** [comment]
Unfortunately it still doesn't work for me - https://codenarc.org/ :

![image](https://user-images.githubusercontent.com/148013/77751740-8d4e2b80-7026-11ea-8671-333cf43b68ba.png)

**Comment by nvuillam** [comment]
Same here, i think the ssl certificate is missing or outdated

**Comment by szpak** [comment]
I would suspect that the `codenarc.org` domain still points to some other server which redirects to GitHub pages instead of has a CNAME record (being an apex domain - without www):
https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by chrismair** [comment]
Okay, I think I finally got this resolved. I added the CNAME record on GitHub, as required. I also removed the forwarding that was on the DNS provider and configured the proper A records. It seems like it works as expected. Closing this issue, but we can certainly reopen if something is still missing.

**Comment by szpak** [comment]
Works perfectly! Thanks for your determination to make it done :-).
